name: seamless_navigation
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.2
  flutter_blue_plus: ^1.10.0
  vector_math: ^2.1.4
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  open_route_service: ^1.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
